name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Rodar ESLint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Rodar testes com Jest
        run: npm test

  # ACTION 1 (Marketplace): aquasecurity/trivy-action
  # Etapa: Security — escaneia o código em busca de vulnerabilidades conhecidas
  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Escanear vulnerabilidades com Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'

  # ACTION 2 (Marketplace): actions/upload-artifact
  # Etapa: Package/Artefatos — empacota os arquivos da aplicação e guarda como artefato do workflow
  package:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gerar artefato do projeto
        uses: actions/upload-artifact@v4
        with:
          name: gerador-de-frases-build
          path: |
            index.html
            style.css
            script.js

  # ACTION 3 (Marketplace): peaceiris/actions-gh-pages
  # Etapa: Deploy — publica a aplicação estática no GitHub Pages
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .