name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test

  # ACTION 1 (Marketplace): aquasecurity/trivy-action
  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'

  # ACTION 2 (Marketplace): actions/upload-artifact
  package:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: gerador-de-frases-build
          path: |
            index.html
            style.css
            script.js

  deploy-dev:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publicando no ambiente de Dev..."

  smoke-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rodando teste rápido de sanidade no ambiente de Dev..."

  deploy-homolog:
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publicando no ambiente de Homologação..."

  # ACTION 3 (Marketplace): peaceiris/actions-gh-pages
  deploy-prod:
    needs: deploy-homolog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .